--------------------------------------------------------------
--------------------------------------------------------------
--                                                          --
-- This VHDL file has been generated by the verilog2vhdl    --
-- tool.                                                    --
-- Contact help@edautils.com  for support/info.--
--                                                          --
--                                                          --
--------------------------------------------------------------
--------------------------------------------------------------
--
--
-- Assumptions: 
--         (1) All the parameters are of type INTEGER, and hence the translated generics are of this type
--
--
-- Generated by : ALLAN on 03/10/18 21:52
--
--
library ieee;
use ieee.std_logic_1164.all;
package vl2vh_common_pack is 
    type vl2vh_memory_type is      array  ( natural range <> , natural range <>  )  of std_logic ;
    function vl2vh_ternary_func(  constant cond : Boolean;  constant trueval : std_logic;  constant falseval : std_logic)  return std_logic; 
    function vl2vh_ternary_func(  constant cond : Boolean;  constant trueval : std_logic_vector;  constant falseval : std_logic_vector)  return std_logic_vector; 
end package; 




package body vl2vh_common_pack is 
    function vl2vh_ternary_func(  constant cond : Boolean;  constant trueval : std_logic;  constant falseval : std_logic)  return std_logic is 
    begin
        if ( cond ) then 
             return trueval;
        else 
             return falseval;
        end if;
    end;
    function vl2vh_ternary_func(  constant cond : Boolean;  constant trueval : std_logic_vector;  constant falseval : std_logic_vector)  return std_logic_vector is 
    begin
        if ( cond ) then 
             return trueval;
        else 
             return falseval;
        end if;
    end;
end; 


library ieee;
library work;
use ieee.std_logic_1164.all;
use ieee.std_logic_misc.all;
use ieee.numeric_std.all;
use work.vl2vh_common_pack.all;
entity Morse is 
     port (
        clock :  inout std_logic;
        reset :  inout std_logic;
        entrada :  inout std_logic;
        saida :  inout std_logic_vector( 7  downto 0  )
    );
end entity; 


architecture rtl of Morse is 
    begin 
    end; 


library ieee;
library work;
use ieee.std_logic_1164.all;
use ieee.std_logic_misc.all;
use ieee.numeric_std.all;
use work.vl2vh_common_pack.all;
entity counter_tb is 
end entity; 


architecture rtl of counter_tb is 
    signal clock : std_logic;
    signal reset : std_logic;
    signal entrada : std_logic;
    signal saida : std_logic_vector( 7  downto 0  );
    component Morse is 
         port (
            clock :  inout std_logic;
            reset :  inout std_logic;
            entrada :  inout std_logic;
            saida :  inout std_logic_vector( 7  downto 0  )
        );
    end component; 
    begin 
        Morse1 : Morse
            port map (
                clock => clock,
                entrada => entrada,
                reset => reset,
                saida => saida
                );
        process 
        begin
            clock <= '0' ;
            reset <= '1' ;
            entrada <= '0' ;
            entrada <= '0' ;
            reset <= '0' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '0' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '1' ;
            entrada <= '0' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '1' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '1' ;
            entrada <= '0' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '1' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '0' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '0' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '1' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '0' ;
            entrada <= '1' ;
            entrada <= '0' ;
            wait ;
        end process;
        process 
        begin
            wait for 5  ns;
            clock <= (  not clock ) ;
        end process;
    end; 
